name: Daily Expense Sync

on:
  schedule:
    - cron: '0 8 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
            python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run File
        env:
          PLAID_CLIENT_ID: ${{ secrets.PLAID_CLIENT_ID }}
          PLAID_SECRET: ${{ secrets.PLAID_SECRET }}
          PLAID_ACCESS_ID: ${{ secrets.PLAID_ACCESS_ID }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python src/plaid_client.py